site_name: Endur
nav: 
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material 
  icon: 
    logo: fontawesome/brands/d-and-d
  features:
  - header.autohide
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.sections
  - navigation.top
  - navigation.path
  - navigation.footer
  - navigation.indexes
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en 
  palette:
  - scheme: slate
    primary: black
    accent: blue grey
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
  - glightbox:
       touchNavigation: true
       loop: false
       effect: none
       width: auto
       height: 100vh
       zoomable: false
       draggable: false
       auto_caption: false
       caption_position: bottom
       background: #000
       shadow: true
       manual: false