site_name: Endur
nav: 
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material 
  features:
  - header.autohide

  - navigation.instant
  - navigation.instant.prefetch
  - navigation.sections
  - navigation.tabs
  - navigation.path
  - navigation.footer
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy 
  language: en 
  palette:
  - scheme: slate
    primary: indigo
    accent: cyan
